# Generated by Django 4.2.30 on 2026-07-21 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="debt",
            name="excel_synced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="debt",
            name="needs_review",
            field=models.BooleanField(default=False),
        ),
    ]
