# Generated by Django 4.2.30 on 2026-07-21 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0002_debt_excel_synced_at_debt_needs_review"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="debt",
            name="creditor",
        ),
        migrations.RemoveField(
            model_name="debt",
            name="source_document",
        ),
        migrations.RemoveField(
            model_name="document",
            name="debt",
        ),
        migrations.DeleteModel(
            name="Creditor",
        ),
        migrations.DeleteModel(
            name="Debt",
        ),
    ]
