# Generated by Django 4.2.30 on 2026-07-21 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0003_remove_debt_creditor_remove_debt_source_document_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="extraction_failed",
            field=models.BooleanField(default=False),
        ),
    ]
